set_property SRC_FILE_INFO {cfile:/home/pablo/git/verilog_dsp/drivers/zmod_dac/xdc/zmod_dac_usb104.xdc rfile:../../../../../../drivers/zmod_dac/xdc/zmod_dac_usb104.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN A13 IOSTANDARD LVCMOS18 } [get_ports { dac_fsi_fs_output }]; #IO_L9P_T1_DQS_AD3P_15 Sch=syzygy_d_p[0]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN A14 IOSTANDARD LVCMOS18 } [get_ports { dac_fsj_fs_output}]; #IO_L9N_T1_DQS_AD3N_15 Sch=syzygy_d_n[0]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN B16 IOSTANDARD LVCMOS18 } [get_ports { dac_ddr_data[13] }]; #IO_L7P_T1_AD2P_15     Sch=syzygy_d_p[1]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN B17 IOSTANDARD LVCMOS18 } [get_ports { dac_ddr_data[12] }]; #IO_L7N_T1_AD2N_15     Sch=syzygy_d_n[1]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN A15 IOSTANDARD LVCMOS18 } [get_ports { dac_rst_spi }]; #IO_L8P_T1_AD10P_15    Sch=syzygy_d_p[2]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN A16 IOSTANDARD LVCMOS18 } [get_ports { dac_spi_sck}]; #IO_L8N_T1_AD10N_15    Sch=syzygy_d_n[2]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN B18 IOSTANDARD LVCMOS18 } [get_ports { dac_ddr_data[11] }]; #IO_L10P_T1_AD11P_15   Sch=syzygy_d_p[3]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN A18 IOSTANDARD LVCMOS18 } [get_ports { dac_ddr_data[10] }]; #IO_L10N_T1_AD11N_15   Sch=syzygy_d_n[3]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN E15 IOSTANDARD LVCMOS18 } [get_ports { dac_spi_sdo}]; #IO_L11P_T1_SRCC_15    Sch=syzygy_d_p[4]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN E16 IOSTANDARD LVCMOS18 } [get_ports { dac_spi_cs }]; #IO_L11N_T1_SRCC_15    Sch=syzygy_d_n[4]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN D15 IOSTANDARD LVCMOS18 } [get_ports { dac_ddr_data[9] }]; #IO_L12P_T1_MRCC_15    Sch=syzygy_d_p[5]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN C15 IOSTANDARD LVCMOS18 } [get_ports { dac_ddr_data[8] }]; #IO_L12N_T1_MRCC_15    Sch=syzygy_d_n[5]
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN C16 IOSTANDARD LVCMOS18 } [get_ports { dac_relay_output }]; #IO_L20P_T3_A20_15     Sch=syzygy_d_p[6]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN C17 IOSTANDARD LVCMOS18 } [get_ports { dac_ddr_data[2] }]; #IO_L20N_T3_A19_15     Sch=syzygy_d_n[6]
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN E18 IOSTANDARD LVCMOS18 } [get_ports { dac_ddr_data[7] }]; #IO_L21P_T3_DQS_15     Sch=syzygy_d_p[7]
set_property src_info {type:XDC file:1 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN D18 IOSTANDARD LVCMOS18 } [get_ports { dac_ddr_data[6] }]; #IO_L21N_T3_DQS_A18_15 Sch=syzygy_d_n[7]
set_property src_info {type:XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN J14 IOSTANDARD LVCMOS18 } [get_ports { dac_ddr_data[4] }];  #IO_L19P_T3_A22_15       Sch=syzygy_s[16]
set_property src_info {type:XDC file:1 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN H15 IOSTANDARD LVCMOS18 } [get_ports { dac_ddr_data[5] }];  #IO_L19N_T3_A21_VREF_15  Sch=syzygy_s[17]
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN G18 IOSTANDARD LVCMOS18 } [get_ports { dac_ddr_data[1] }];  #IO_L22P_T3_A17_15       Sch=syzygy_s[18]
set_property src_info {type:XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN F18 IOSTANDARD LVCMOS18 } [get_ports { dac_ddr_data[0] }];  #IO_L22N_T3_A16_15       Sch=syzygy_s[19]
set_property src_info {type:XDC file:1 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN J17 IOSTANDARD LVCMOS18 } [get_ports { dac_ddr_data[3] }];  #IO_L23P_T3_FOE_B_15     Sch=syzygy_s[20]
set_property src_info {type:XDC file:1 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN H16 IOSTANDARD LVCMOS18 } [get_ports { dac_ddr_clk }]; #IO_L13P_T2_MRCC_15 Sch=syzygy_p2c_clk_p
set_property src_info {type:XDC file:1 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN F15 IOSTANDARD LVCMOS18 } [get_ports { dac_clkin }]; #IO_L14P_T2_SRCC_15 Sch=syzygy_c2p_clk_p
