# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/pablo/git/verilog_dsp/usb104_qam16/project/usb104_qam/usb104_qam.srcs/sources_1/bd/qam16_bd/ip/qam16_bd_fir_compiler_0_1/qam16_bd_fir_compiler_0_1.xci
# IP: The module: 'qam16_bd_fir_compiler_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/pablo/git/verilog_dsp/usb104_qam16/project/usb104_qam/usb104_qam.gen/sources_1/bd/qam16_bd/ip/qam16_bd_fir_compiler_0_1/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'qam16_bd_fir_compiler_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/pablo/git/verilog_dsp/usb104_qam16/project/usb104_qam/usb104_qam.gen/sources_1/bd/qam16_bd/ip/qam16_bd_fir_compiler_0_1/qam16_bd_fir_compiler_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'qam16_bd_fir_compiler_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/pablo/git/verilog_dsp/usb104_qam16/project/usb104_qam/usb104_qam.srcs/sources_1/bd/qam16_bd/ip/qam16_bd_fir_compiler_0_1/qam16_bd_fir_compiler_0_1.xci
# IP: The module: 'qam16_bd_fir_compiler_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/pablo/git/verilog_dsp/usb104_qam16/project/usb104_qam/usb104_qam.gen/sources_1/bd/qam16_bd/ip/qam16_bd_fir_compiler_0_1/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'qam16_bd_fir_compiler_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/pablo/git/verilog_dsp/usb104_qam16/project/usb104_qam/usb104_qam.gen/sources_1/bd/qam16_bd/ip/qam16_bd_fir_compiler_0_1/qam16_bd_fir_compiler_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'qam16_bd_fir_compiler_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
