# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/pablo/git/verilog_dsp/drivers/zmod_dac/xdc/zmod_dac_usb104.xdc

# Block Designs: bd/qam16_bd/qam16_bd.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==qam16_bd || ORIG_REF_NAME==qam16_bd} -quiet] -quiet

# IP: bd/qam16_bd/ip/qam16_bd_fir_compiler_0_0/qam16_bd_fir_compiler_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==qam16_bd_fir_compiler_0_0 || ORIG_REF_NAME==qam16_bd_fir_compiler_0_0} -quiet] -quiet

# IP: bd/qam16_bd/ip/qam16_bd_fir_compiler_0_1/qam16_bd_fir_compiler_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==qam16_bd_fir_compiler_0_1 || ORIG_REF_NAME==qam16_bd_fir_compiler_0_1} -quiet] -quiet

# IP: bd/qam16_bd/ip/qam16_bd_clk_wiz_0_0/qam16_bd_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==qam16_bd_clk_wiz_0_0 || ORIG_REF_NAME==qam16_bd_clk_wiz_0_0} -quiet] -quiet

# IP: bd/qam16_bd/ip/qam16_bd_qam16_data_packet_0_0/qam16_bd_qam16_data_packet_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==qam16_bd_qam16_data_packet_0_0 || ORIG_REF_NAME==qam16_bd_qam16_data_packet_0_0} -quiet] -quiet

# IP: bd/qam16_bd/ip/qam16_bd_system_ila_0_0/qam16_bd_system_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==qam16_bd_system_ila_0_0 || ORIG_REF_NAME==qam16_bd_system_ila_0_0} -quiet] -quiet

# IP: bd/qam16_bd/ip/qam16_bd_qam16_data_generator_0_0/qam16_bd_qam16_data_generator_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==qam16_bd_qam16_data_generator_0_0 || ORIG_REF_NAME==qam16_bd_qam16_data_generator_0_0} -quiet] -quiet

# IP: bd/qam16_bd/ip/qam16_bd_qam16_data_upsampler_0_0/qam16_bd_qam16_data_upsampler_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==qam16_bd_qam16_data_upsampler_0_0 || ORIG_REF_NAME==qam16_bd_qam16_data_upsampler_0_0} -quiet] -quiet

# IP: bd/qam16_bd/ip/qam16_bd_xlslice_0_0/qam16_bd_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==qam16_bd_xlslice_0_0 || ORIG_REF_NAME==qam16_bd_xlslice_0_0} -quiet] -quiet

# IP: bd/qam16_bd/ip/qam16_bd_xlslice_0_1/qam16_bd_xlslice_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==qam16_bd_xlslice_0_1 || ORIG_REF_NAME==qam16_bd_xlslice_0_1} -quiet] -quiet

# IP: bd/qam16_bd/ip/qam16_bd_axis_zmod_dac_v1_0_0_0/qam16_bd_axis_zmod_dac_v1_0_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==qam16_bd_axis_zmod_dac_v1_0_0_0 || ORIG_REF_NAME==qam16_bd_axis_zmod_dac_v1_0_0_0} -quiet] -quiet

# IP: bd/qam16_bd/ip/qam16_bd_xlconcat_0_0/qam16_bd_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==qam16_bd_xlconcat_0_0 || ORIG_REF_NAME==qam16_bd_xlconcat_0_0} -quiet] -quiet

# IP: bd/qam16_bd/ip/qam16_bd_oddr_0_0/qam16_bd_oddr_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==qam16_bd_oddr_0_0 || ORIG_REF_NAME==qam16_bd_oddr_0_0} -quiet] -quiet

# XDC: /home/pablo/git/verilog_dsp/usb104_qam16/project/usb104_qam/usb104_qam.gen/sources_1/bd/qam16_bd/qam16_bd_ooc.xdc
